<?php
	$dir_archivos_permisos = "\\\\192.168.1.126\\permisos\\";
	$URL_archivos_permisos = "http://www.delbravoweb.com/docs_permisos/";
	$red_archivos_permisos = "\\\\192.168.1.126\\permisos\\";
	$dir_archivos_facturas = "\\\\192.168.1.126\\documentos_expo\\cruces\\";
	$URL_archivos_facturas = "http://www.delbravoweb.com/documentos_expo/cruces/";
	$red_archivos_facturas = "\\\\192.168.1.126\\documentos_expo\\cruces\\";
	$dir_archivos_certificados_origen = "\\\\192.168.1.126\\certificados_origen\\";
	$URL_archivos_certificados_origen  = "http://www.delbravoweb.com/docs_certificados_origen/";
	$red_archivos_certificados_origen  = "\\\\192.168.1.126\\certificados_origen\\";
	$dir_archivos_pedimentos = "\\\\192.168.1.126\\Pedimentos2009\\";
	$URL_archivos_pedimentos="https://www.delbravoweb.com/pedimentos/";
	$dir_rpt_relacion_servicios="\\\\192.168.1.234\\WebSites\\monitor\\panel\\";
	$dir_archivos_web = "\\\\192.168.1.126\\archivos_web\\";
	$dir_server_web = "\\\\192.168.1.126\\";
	$dir_archivos_gabdata = "\\\\192.168.1.107\\gabdata\\";
	$dir_archivos_cfd = "\\\\192.168.1.126\\cfd\\";
	$URL_archivos_anexos = "https://www.delbravoweb.com/anexos/";
	$dir_archivos_anexos_gab = "\\\\192.168.1.126\\cfd\\anexos\\";	
	$URL_bodega = "http://delbravoapps.tk/";/*"https://192.168.2.51/";*/
	$URL_ws_webtools = "http://delbravoapps.tk/";
	$dir_archivos_temp_cruces = "C:\\WebSites\\monitor\\panel\\ajax\\cruces_exportacion\\Archivos_Temporales\\";